# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Corazon', '0002_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doctor1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Corazon.Doctor'),
        ),
    ]
