# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Corazon', '0003_paciente_doctor1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinica',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sexo',
            field=models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=2),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='doctor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Corazon.Doctor'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=2),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
