# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corazon', '0004_auto_20160611_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2),
        ),
    ]
