# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 04:01
from __future__ import unicode_literals

import Corazon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corazon', '0007_doctor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=Corazon.models.url),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=Corazon.models.url),
        ),
    ]
