# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 15:26
from __future__ import unicode_literals

import Corazon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corazon', '0008_auto_20160615_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=Corazon.models.url2),
        ),
    ]
