# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Corazon', '0010_auto_20160701_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('send_mail', 'Puede enviar mails'),)},
        ),
    ]
