# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corazon', '0011_auto_20160701_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
