# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 17:35
from __future__ import unicode_literals

import Corazon.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corazon', '0012_auto_20160707_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cedula',
            field=models.CharField(max_length=10, validators=[Corazon.validators.validacion_10digit, Corazon.validators.validacion_esDigito]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[Corazon.validators.validacion_esDigito]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=10, validators=[Corazon.validators.validacion_10digit, Corazon.validators.validacion_esDigito]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.CharField(max_length=3, validators=[Corazon.validators.validacion_esDigito]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[Corazon.validators.validacion_esDigito]),
        ),
    ]
