# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_envio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
