# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Corazon', '0009_auto_20160618_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pac1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Corazon.Paciente')),
            ],
        ),
    ]
